runtime: php72

handlers:
  - url: /
    static_dir: public/    



env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:2yWnWJpy4ueRAUiQvePzT51bhqf9YnqMbY/gHF160mc=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie