runtime: php72

handlers:
  - url: /css
    static_dir: public/css

  - url: /js
    static_dir: public/js 
    
  - url: /img
    static_dir: public/img   

  - url: /images
    static_dir: public/images     

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:2yWnWJpy4ueRAUiQvePzT51bhqf9YnqMbY/gHF160mc=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie