runtime: php72

handlers:
  - url: /css
    static_dir: public/css

  - url: /js
    static_dir: public/js 
    
  - url: /img
    static_dir: public/img   

  - url: /images
    static_dir: public/images  

 # Serve images as static resources.
  - url: /(.+\.(gif|png|jpg))$
    static_files: \1
    upload: public/.*\.(gif|png|jpg|css|js)$

# Serve your app through a front controller at index.php or public/index.php.
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:2yWnWJpy4ueRAUiQvePzT51bhqf9YnqMbY/gHF160mc=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
  
  DB_DATABASE: creamline_db
  DB_USERNAME: root
  DB_PASSWORD: 12345
  ## for MYSQL, use DB_SOCKET:
  DB_SOCKET: "/cloudsql/testingcharp:asia-southeast2:testingcharpling"
  ## for PostgreSQL, use DB_HOST:
  # DB_HOST: "/cloudsql/YOUR_CONNECTION_NAME" 