runtime: php72

handlers:
  - url: /css
    static_dir: public/css

  - url: /js
    static_dir: public/js 
    
  - url: /img
    static_dir: public/img   

  - url: /images
    static_dir: public/images  

 # Serve images as static resources.
  - url: /(.+\.(gif|png|jpg))$
    static_files: \1
    upload: .+\.(gif|png|jpg)$

# Serve your app through a front controller at index.php or public/index.php.
  - url: .*
    script: auto      

env_variables:
  ## Put production environment variables here.
  APP_KEY: base64:2yWnWJpy4ueRAUiQvePzT51bhqf9YnqMbY/gHF160mc=
  APP_STORAGE: /tmp
  VIEW_COMPILED_PATH: /tmp
  SESSION_DRIVER: cookie
  DB_DATABASE: creamline_db
  DB_USERNAME: root
  DB_PASSWORD: caAwDGeA62hdmksK
  ## for MYSQL, use DB_SOCKET:
  DB_SOCKET: "/cloudsql/charplingenterprise:us-central1:dbcreamline"
  ## for PostgreSQL, use DB_HOST:
  # DB_HOST: "/cloudsql/YOUR_CONNECTION_NAME"